### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by Semigradsky** [polemius/postcss-clamp#2]
**Thanks for your PostCSS plugin!**

As you probably know, PostCSS 8 was released a few days ago. It would be great if you could make this plugin compatible with the latest version. The creators of the project have even released this [migration guide](https://evilmartians.com/chronicles/postcss-8-plugin-migration).

**Comment by Semigradsky** [comment]
@polemius could you please release?

**Comment by polemius** [comment]
@Semigradsky Released in 2.0.0
