### ISSUE TITLE
Doesn't compile if the middle value is a calc

### ISSUE THREAD

**Issue by soilysound** [polemius/postcss-clamp#20]
This compiles to the nested max/min: 
`font-size: clamp(12px, 2vw, 16px);`

but this doesn't:
`font-size: clamp(12px, 2vw + 1px, 16px);`

**Comment by polemius** [comment]
To calculate value you need to use `calc`:

`font-size: clamp(12px, calc(2vw + 1px), 16px);`

And this will complies to the nested max/min

**Comment by soilysound** [comment]
Thanks, although the spec doesn't require the extra calc inside a clamp, min or max, as they act as calcs themselves.
